### ISSUE TITLE
How does fitbert handle answers that have multiple tokens?

### ISSUE THREAD

**Issue by mannt-jp** [writerai/fitbert#22]
If the answer contains multiple tokens (for example containing multiple words, or even a whole sentence), how does fitbert compute the cummulative probability of this kind of answer. Because MLM outputs the probabilities for every single tokens, not for groups of tokens.

**Comment by sam-writer** [comment]
I would use BART for this, see https://github.com/writerai/fitbert/issues/19#issuecomment-913618892
